name: Build on Windows (x64 only)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    name: Build x86_64
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-miniupnpc
        update: true

    - name: Build application
      run: |
        mkdir -p obj/Win32 obj/libi2pd obj/libi2pd_client obj/daemon
        make USE_UPNP=yes DEBUG=no USE_GIT_VERSION=yes -j3

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i2pd-x64.exe
        path: i2pd.exe
